### ISSUE TITLE
`cargo run` fails

### ISSUE THREAD

**Issue by mturquette** [oh-yes-0-fps/D2_Calculation_API#1]
Hi,

I'm trying to run D2_Calcuation_API for the first time. I'm able to successfully build with `cargo build`, but I get the following error when I try to run it:

```
$ cargo run
error: a bin target must be available for `cargo run`
$ cargo install
error: no packages found with binaries or examples
```

Any hints on what I'm doing wrong? This is on Mac OS Ventura 13.1 with an ARM-based Mackbook Air M2, if that makes any difference. Rust toolchain is up to date, as is cargo.

**Comment by oh-yes-0-fps** [comment]
Hi, this project is not meant to be "run" and is still in beta so i not have fully written up compile instructions. If you want a wasm binary with JavaScript bindings install wasm-pack and run with '--features wasm'. If you desire python run a cargo build with '--features python' and take the .dll compiled and rename it to a .pyd for windows or a .so for mac I believe. Look at pyo3 documentation if you need more help with python. 
A note is if your using it for js the zip included does not need recompiling for arm as the JS runtime will translate the wasm for u
Final note is its not meant to be called from other rust crates but features like that and c# bindings are coming in the near future
